# Generated by Django 4.1.3 on 2022-11-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questio_text',
            new_name='question_text',
        ),
    ]
